name: Build and publish docs

on:
  workflow_run:
    workflows: ["Python Tests"]

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install -E docs
      - name: Build docs
        run: |
          poetry run pdoc src/textknnassifier -o docs
          touch docs/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
